### ISSUE TITLE
Box JWT Authentication: New Permission Error

### ISSUE THREAD

**Issue by kdomsohn** [box/box-python-sdk-gen#190]
Hello,

I ran into a new issue where I am unable to change the Box status of an admin user. This is something my script has been doing for over 2 years now but stopped working sometime in the past few weeks. Have there been updates to limit the scope of JWT authentication? The Box dev app has not been changed either. 

Any help would be appreciate and can provide any more information needed. 

Thanks, 
Kyle

**Comment by kdomsohn** [comment]
Hi @mwwoda,

Appreciate your response. Yes I agree that this appears to be something outside of the SDK and I created a ticket with Box. 

Also, for more information I am able to change the status of managed users and admin users but unable to for the Primary Admin. 

Sample of the code below:

def switch_user_status(client, user_id, to_inactive=True):
    '''
    Switch the user's status to or from "inactive" status
    given a Box user ID.
    '''
    user = client.user(user_id).get()
    print(f"User: {user.name}-User ID: {user.id}")
    if to_inactive:
        user.update_info(data = {'status': 'inactive'})
    else:
        user.update_info(data = {'status': 'active'})    
    return

**Comment by lukaszsocha2** [comment]
Hi @kdomsohn,
did you manage to resolve this issue ?

**Comment by kdomsohn** [comment]
Hi @lukaszsocha2,

Yes, I spoke with Box support and it appears that the functionality to change the status Primary Admin was never suppose to be available. So it appears their engineering team did a shadow update to block this function. 

Thanks, 
Kyle

**Comment by lukaszsocha2** [comment]
Hi, 
thanks for a response. As this is not a SDK issue I'm closing this issue, but feel free to reopen it if needed.
Best,
@lukaszsocha2
