### ISSUE TITLE
Signature validation function for Webhook manager

### ISSUE THREAD

**Issue by jstinsonCCHMC** [box/box-python-sdk-gen#219]
### Is your feature request related to a problem? Please describe.

In the previous Box Python SDK, the Webhooks object had a function "validate_message" which validated a box webhook payload given your signature keys. This is missing in the new Webhook manager.

### Describe the solution you'd like

Add this helper function to the Webhook manager

### Describe alternatives you've considered

Easy to do manually, but it is described in current box documentation as "provided for your convenience in the official Box SDKs".

**Comment by mwwoda** [comment]
Hi @jstinsonCCHMC 
Thank you for raising this issue. Signature validation is indeed on our roadmap, but I can't give an exact timeframe for when it's coming to the SDK. I will forward this to the team so that we can prioritize it.
