### ISSUE TITLE
Sudden 'Invalid_grant' Error with using CCG auth flow

### ISSUE THREAD

**Issue by Blaygh** [box/box-python-sdk-gen#220]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
 https://forum.box.com/t/sudden-invalid-grant-using-ccg-authenticiation/2581?u=nana 
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue

I get the following error when I try to upload files to box. {‘error’: ‘invalid_grant’, ‘error_description’: ‘Grant credentials are invalid’}
#011Raw body: {“error”:“invalid_grant”,“error_description”:“Grant credentials are invalid”} CODE: 400
I have been using the same code to do this for the past 20 days and all of a sudden yesterday i start o get this error. I have not changed the code, i have confirmed the the payload is valid, I have reconfirmed the account secrets and other credentials.
I am using CLIENT CEDENTIAL GRANT, I don’t know what to do this point. my
Client ID is: jygzytv1jgtixjtbbipwdfa5m2yh4k4u

### Error Message, Including Stack Trace

below is the full error message

Underlying error: None
Message: 400 ; Request ID:
Request:
#011Method: POST
#011URL: url
#011Query params:
{}
#011Headers:
{ ‘Content-Type’: ‘application/x-www-form-urlencoded’,
‘User-Agent’: ‘box-python-generated-sdk-1.1.0’,
‘X-Box-UA’: ‘agent=box-python-generated-sdk/1.1.0; env=python/3.10.5’}
#011Body:
Response:
#011Status code: 400
#011Headers:
{ ‘Alt-Svc’: ‘h3=“:443”; ma=2592000,h3-29=“:443”; ma=2592000’,
‘Cache-Control’: ‘no-store’,
‘Content-Type’: ‘application/json’,
‘Date’: ‘Thu, 11 Jul 2024 16:36:04 GMT’,
#011Request Id: None
#011Help Url: None
#011Body:
{‘error’: ‘invalid_grant’, ‘error_description’: ‘Grant credentials are invalid’}
#011Raw body: {“error”:“invalid_grant”,“error_description”:“Grant credentials are invalid”} CODE: 400

### Versions Used

Python SDK: 
Python: 

[sdk-docs]: https://github.com/box/box-python-sdk-gen/tree/main/docs
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-python-sdk-gen/search?type=Issues

**Comment by mwwoda** [comment]
Looks similar to https://github.com/box/box-python-sdk-gen/issues/217. Can you try testing the same API call (https://developer.box.com/reference/post-oauth2-token/) with cURL to check if the SDK is causing the issue?

**Comment by Blaygh** [comment]
> Looks similar to #217. Can you try testing the same API call (https://developer.box.com/reference/post-oauth2-token/) with cURL to check if the SDK is causing the issue?

thanks for your reply, but i am getting the same error as I did when using sdk 

HTTP/2 400 
date: Fri, 12 Jul 2024 18:59:56 GMT
content-type: application/json
strict-transport-security: max-age=31536000
set-cookie: box_visitor_id=66917d27420722; expires=Sat, 12-Jul-2025 18:59:56 GMT; Max-Age=31536000; path=/; domain=.box.com;
 secure; SameSite=None
set-cookie: bv=SHIELD-40151; expires=Fri, 19-Jul-2024 18:59:56 GMT; Max-Age=604800; path=/; domain=.app.box.com; secure
set-cookie: cn=29; expires=Sat, 12-Jul-2025 18:59:56 GMT; Max-Age=31536000; path=/; domain=.app.box.com; secure
set-cookie: site_preference=desktop; path=/; domain=.box.com; secure
cache-control: no-store
via: 1.1 google
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
{"error":"invalid_grant","error_description":"Grant credentials are invalid"}18:59

**Comment by congminh1254** [comment]
Hi @Blaygh 

I got an answer from the team, they said that we have a security policy applied recently, but most of the customers should be exempt, but it might affect the apps created very recently.

To fix the issue, you have to upgrade the app’s access level to “App + Enterprise Access” from the developer console and then do a re-authorization.

We are sorry for the trouble.

Bests,
Minh
