### ISSUE TITLE
I guess the docs has a misstake. 

### ISSUE THREAD

**Issue by c-rei** [box/box-python-sdk-gen#243]
The docs for OAuth2 auth has a sample code like below, but I got an error "TypeError: BoxOAuth.get_authorize_url() takes 1 positional argument but 2 were given".

So I checked up the SDK code for get_authorize_url, and changed 
  auth_url = AUTH.get_authorize_url(GetAuthorizeUrlOptions(redirect_uri="YOUR_REDIRECT_URL"))
to 
  auth_url = AUTH.get_authorize_url(options=GetAuthorizeUrlOptions(redirect_uri="YOUR_REDIRECT_URL"))
, then it worked.

**** sample code ****
from flask import Flask, request, redirect
from box_sdk_gen import BoxClient, BoxOAuth, OAuthConfig, GetAuthorizeUrlOptions
app = Flask(__name__)
AUTH = BoxOAuth(
    OAuthConfig(client_id="YOUR_CLIENT_ID", client_secret="YOUR_CLIENT_SECRET")
)
@app.route("/")
def get_auth():
    auth_url = AUTH.get_authorize_url(
        GetAuthorizeUrlOptions(redirect_uri="YOUR_REDIRECT_URL")
    )
    return redirect(auth_url, code=302)
@app.route("/oauth2callback")
def callback():
    AUTH.get_tokens_authorization_code_grant(request.args.get("code"))
    client = BoxClient(AUTH)

    items_in_root_folder = [
        item.name for item in client.folders.get_folder_items(folder_id="0").entries
    ]
    return ", ".join(items_in_root_folder)
if __name__ == "__main__":
    app.run(port=4999)
**** code end ****

### Versions Used

Python SDK: 1.1.0
Python: 3.10.12

**Comment by lukaszsocha2** [comment]
Hi @c-rei,
thanks for reaching us and telling us about a bug in docs. We will fix it soon.
Best,
@lukaszsocha2
