### ISSUE TITLE
I have a question about jwt.

### ISSUE THREAD

**Issue by c-rei** [box/box-python-sdk-gen#246]
### Description of the Issue
I tried to install jwt package follow your command "pip install box-sdk-gen[jwt]", I got an error message like this "no matches found: box-sdk-gen[jwt]".
But when I tried the sample code of the docs for jwt authentication, it worked. So I want to known what's wrong when I use jwt issues?

### Versions Used

Python SDK: 1.1.0
Python: 3.10.12

**Comment by arjankowski** [comment]
Hi @c-rei,
This command might not work because of the brackets: `[` and `]` which have special meanings in the shell. 

Therefore, if you encounter this problem, to install this package you should enclose the entire package name in quotation marks: 
```
pip install "box-sdk-gen[jwt]"
```

I hope this helps!

**Comment by c-rei** [comment]
Thanks for your help, it worked.
