### ISSUE TITLE
I have a request.

### ISSUE THREAD

**Issue by c-rei** [box/box-python-sdk-gen#247]
I'am trying the code of the documents, but I'm having trouble finding out where the packages came from.
So I hope that give us any import required in your code.

Thanks.

### Versions Used

Python SDK: 1.1.0
Python: 3.10.12

**Comment by arjankowski** [comment]
Hi @c-rei, 
I am not sure if I understand the question correctly, but if you are asking where the packages come from, they are located in the PyPI repository here: https://pypi.org/project/box-sdk-gen/.

However, if you are asking where to import the classes you want to use in your code from, all classes are available from the main package `box_sdk_gen`.
So if you want to use a specific class, you just need to add the appropriate import. 
For example, to upload a file using the classes `UploadFileAttributes`,` Files`, and `File`, your code along with the imports should look like this:

```
from box_sdk_gen import BoxClient, BoxJWTAuth, JWTConfig, UploadFileAttributes, UploadFileAttributesParentField, Files, File

jwt_config = JWTConfig.from_config_file(config_file_path="config.json")
auth = BoxJWTAuth(config=jwt_config)
client = BoxClient(auth=auth)

attrs = UploadFileAttributes(
    name="filename.txt", parent=UploadFileAttributesParentField(id="0")
)
files: Files = client.uploads.upload_file(
    attributes=attrs, file=open("filename.txt", "rb")
)
file: File = files.entries[0]
print(f"File uploaded with id {file.id}, name {file.name}")
```

**Comment by c-rei** [comment]
Hi, @arjankowski,
My question just is where to import classes I want to use, for example the sample code,

client.file_metadata.get_file_metadata_by_id(
    file.id, GetFileMetadataByIdScope.GLOBAL.value, "properties"
)

I want to known where to import GetFileMetadataByIdScope etc.

**Comment by arjankowski** [comment]
You import the classes from the .py file that uses them.

**Comment by lukaszsocha2** [comment]
You cna import everything from the main package `box_sdk_gen`, e.g.
`from box_sdk_gen import GetFileMetadataByIdScope`
Best, 
@lukaszsocha2

**Comment by c-rei** [comment]
Hi, @lukaszsocha2,
Thank you very much. I known to import everything from main box_sdk_gen.

Hi, @arjankowski,
I known how to import some thing from .py file, but I must to investigate much .py file to find them.
Thanks.
