### ISSUE TITLE
I'm sorry for asking so many times, but

### ISSUE THREAD

**Issue by c-rei** [box/box-python-sdk-gen#248]
I use OAuth2 Auth for my applications with box-python-sdk, and I storage access_token and refresh_token when the user login box first time. The sample code like below. Then I don't need to login box again while next running.

**** sample code start ****
from boxsdk import Client, OAuth2

oauth = OAuth2(
    client_id='YOUR_CLIENT_ID',
    client_secret='YOUR_CLIENT_SECRET',
    access_token='ACCESS_TOKEN',
    refresh_token='REFRESH_TOKEN',
)

client = Client(oauth)

user = client.user().get()
print(f'User ID is {user.id}')
**** end ****

With box-python-sdk-gen, I read the documents, and known how to storage the token like below, but I don't understand how to get a client with token_storage, so I don't need to login box again like the box-python-sdk as mentioned above.

Thanks any help.

***** sample code *****
from box_sdk_gen import BoxOAuth, OAuthConfig, FileTokenStorage

auth = BoxOAuth(
    OAuthConfig(
        client_id="YOUR_CLIENT_ID",
        client_secret="YOUR_CLIENT_SECRET",
        token_storage=FileTokenStorage(),
    )
)
***** end *****

### Versions Used

Python SDK: 1.1.0
Python: 3.10.12

**Comment by lukaszsocha2** [comment]
Hi @c-rei,
you create it the same way as before:
```from box_sdk_gen import BoxOAuth, OAuthConfig, FileTokenStorage

auth = BoxOAuth(
  OAuthConfig(
  client_id="YOUR_CLIENT_ID",
  client_secret="YOUR_CLIENT_SECRET",
  token_storage=FileTokenStorage(),
  )
)
client = Client(auth)
```
FileTokenStorage will be utilised automatically. However I recommend using `FileWithInMemoryCacheTokenStorage` for the better performance.
Best,
@lukaszsocha2

**Comment by lukaszsocha2** [comment]
Hi @c-rei,
you can use a sample below:
```
from box_sdk_gen import BoxOAuth, OAuthConfig, FileWithInMemoryCacheTokenStorage, AccessToken

auth = BoxOAuth(
  OAuthConfig(
  client_id="YOUR_CLIENT_ID",
  client_secret="YOUR_CLIENT_SECRET",
  token_storage=FileWithInMemoryCacheTokenStorage(AccessToken(refresh_token='YOUR TOKEN')),
  )
)
auth.token_storage.store()
```
Best,
@lukaszsocha2

**Comment by c-rei** [comment]
Hi, @lukaszsocha2,
Thanks your responses. I got it. sample code like this, and /retry routine is second run.

from flask import Flask, request, redirect

from box_sdk_gen import BoxClient, BoxOAuth, OAuthConfig, GetAuthorizeUrlOptions, FileTokenStorage, AccessToken

app = Flask(__name__)

AUTH = BoxOAuth(
    OAuthConfig(client_id="f21sztnm0ocfdcoajhqez4gxbq8hkq1h",
                client_secret="bA8E9DvW0KPuPhhUXimNJNeJUqLsXTIa",
                token_storage=FileTokenStorage(),)
)

ops = GetAuthorizeUrlOptions(redirect_uri="http://localhost:8080/oauth")

@app.route("/retry")
def retry():
    token = AUTH.retrieve_token()
    AUTH.token_storage.store(AccessToken(access_token=token.access_token, refresh_token=token.refresh_token))
    client = BoxClient(AUTH)
    me = client.users.get_user_me()
    return me.id


@app.route("/")
def get_auth():
    auth_url = AUTH.get_authorize_url(options=ops)
    return redirect(auth_url, code=302)


@app.route("/oauth")
def callback():
    AUTH.get_tokens_authorization_code_grant(request.args.get("code"))
    client = BoxClient(AUTH)

    items_in_root_folder = [
        item.name for item in client.folders.get_folder_items(folder_id="0").entries
    ]
    return ", ".join(items_in_root_folder)


if __name__ == "__main__":
    app.run(port=8080)

**Comment by arjankowski** [comment]
Hi @c-rei,
Do you have any more specific questions regarding this issue?

**Comment by lukaszsocha2** [comment]
Hi @c-rei,
we have deleted your message, because you were exposing you secrets in the code sample. You are free to repost that again without any sensitive infomation. I also recommend to revoke your `client_secret` now and generate a new one.
Best,
@lukaszsocha2

**Comment by c-rei** [comment]
Hi, @lukaszsocha2,
Thank you for your help. I forgot to hide my client_secret.
As your recommended, I'v revoke my client_secret.
Thanks.
