### ISSUE TITLE
migration from box-sdk Upload new version of file

### ISSUE THREAD

**Issue by nrclark38258** [box/box-python-sdk-gen#249]
I have been looking through the sdk-gen documentation and am trying to find how to upload a new version of a file. The 'uploads.md' method works if I upload a brand new file, but get an error "name in use" when the file already exists.

The previous sdk had .update_contents(), but I'm not finding an equivalent here.

Thank you

**Comment by lukaszsocha2** [comment]
Hi @nrclark38258,
thanks for reaching us. You can use `upload_file_version` method from `UploadsManager`. Sample code:
``` 
new_files: Files = client.uploads.upload_file_version(file.id, UploadFileVersionAttributes(name=new_name), open('filename.txt', 'rb'))
new_file: FileFull = new_files.entries[0]
```
We will add missing methods to the uploads.md file soon.
Best,
@lukaszsocha2

**Comment by nrclark38258** [comment]
Excellent, thank you!
