### ISSUE TITLE
Methods remove_shared_link_from_folder and remove_shared_link_from_file are unable to remove the shared link.

### ISSUE THREAD

**Issue by fujita-h** [box/box-python-sdk-gen#259]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ ] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue

`client.shared_links_folders.remove_shared_link_from_folder` and `client.shared_links_files.remove_shared_link_from_file` are unable to remove the shared link.

### Steps to Reproduce

1. Create a folder of file with a shared link and get its id.
2. Using box_sdk_gen, do the following:
```
client = BoxClient(auth=auth)
client.shared_links_folders.remove_shared_link_from_folder(<ID>, "shared_link")
```
3. Verify that the shared link for the specified item has not been deleted.

### Expected Behavior

The expected behavior is that the shared link for the specified item will be deleted.

### Error Message, Including Stack Trace

The API for deleting a shared link expects "shared_link" to be set to null in the request body.
Ref: https://developer.box.com/reference/put-folders-id--remove-shared-link/

The SDK functions construct the request body from the arguments and store it in request_body.
Since we are trying to delete a shared link, this value will basically be stored as `None`.
https://github.com/box/box-python-sdk-gen/blob/bca02d362f7d16de842ba6db695e2b0e12cf95b1/box_sdk_gen/managers/shared_links_folders.py#L518

When this value is fetched by the API, it is serialized by `serialize` and stored in the value.
https://github.com/box/box-python-sdk-gen/blob/bca02d362f7d16de842ba6db695e2b0e12cf95b1/box_sdk_gen/managers/shared_links_folders.py#L534

The body sent in this case is expected to be `{"shared_link": null} `.
But the request body being sent was an empty JSON object `{}`.

I think it's due to the serialization process, but I haven't tracked it down any further. Looking at the code, I think this is the most likely cause.

https://github.com/box/box-python-sdk-gen/blob/bca02d362f7d16de842ba6db695e2b0e12cf95b1/box_sdk_gen/internal/base_object.py#L28-L30

### Versions Used

Python SDK: 1.2.0
Python: 3.11

[sdk-docs]: https://github.com/box/box-python-sdk-gen/tree/main/docs
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-python-sdk-gen/search?type=Issues

**Comment by mwwoda** [comment]
I believe that when null value is expected by the API you need to explicitly set it in the SDK. Here's the representation of null value used in Python SDK https://github.com/box/box-python-sdk-gen/blob/main/box_sdk_gen/internal/null_value.py. Here's the example how to use it https://github.com/box/box-python-sdk-gen/blob/main/test/files.py#L122.

In your case it should be something like this
```
from box_sdk_gen.internal.utils import create_null
client = BoxClient(auth=auth)
client.shared_links_folders.remove_shared_link_from_folder(<ID>, shared_link=create_null())
```

**Comment by fujita-h** [comment]
Thank you. I understand the intention of the implementation.
The function name is `remove_shared_link_from_folder`, and the argument `shared_link` is optional, so I misunderstood that the deletion would be performed without this argument.
