### ISSUE TITLE
Message: Developer token has expired. Please provide a new one.

### ISSUE THREAD

**Issue by marinabuezo** [box/box-python-sdk-gen#298]
### Description of the Issue

I am trying to use https://github.com/box/box-python-sdk-gen?tab=readme-ov-file#installing to connect to box so that I can download and upload files. I have tried getting a Developer Token from the Configuration page  and inserting into code. I then try to run the code but get this issue: Message: Developer token has expired. Please provide a new one.

### Steps to Reproduce
- pip install box-sdk-gen
- copy code: 
- from box_sdk_gen import BoxClient, BoxDeveloperTokenAuth

def main(token: str):
    auth: BoxDeveloperTokenAuth = BoxDeveloperTokenAuth(token=token)
    client: BoxClient = BoxClient(auth=auth)
    for item in client.folders.get_folder_items('0').entries:
        print(item.name)

if __name__ == '__main__':
    main('INSERT YOUR DEVELOPER TOKEN HERE')

- I Insert my developer token from configuration page 
- I run script 
- gives me error 
### Expected Behavior

I expected it to be able to connect to my box 

### Screenshots

attached
<img width="1064" alt="Screenshot 2024-09-04 at 2 07 23 PM" src="https://github.com/user-attachments/assets/bb289282-4311-4716-9f53-208e3abec274">

### Versions Used

Python: Python 3.11.8

[sdk-docs]: https://github.com/box/box-python-sdk-gen/tree/main/docs
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-python-sdk-gen/search?type=Issues

**Comment by mwwoda** [comment]
Developer tokens are usually short-lived. It is possible that yours has expired before the call was made. You can try making the same call with cURL to make sure it's not a problem with the SDK itself - https://developer.box.com/reference/get-folders-id/

```
curl -i -X GET "https://api.box.com/2.0/folders/0" \
     -H "authorization: Bearer <ACCESS_TOKEN>"
```
If problem still persist I recommend reaching out to our [forums](https://community.box.com/)

**Comment by lukaszsocha2** [comment]
Hi @marinabuezo,
did you manage to resolve your issue?
