### ISSUE TITLE
Cooperatively Managed OAuth

### ISSUE THREAD

**Issue by tribloom** [box/box-python-sdk-gen#33]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ ] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue

I am interested in potentially migrating from the box-python-sdk since this SDK supports API calls that the old SDK does not. Are there any plans to support collaboratively managed oath such as in the old box SDK (https://github.com/box/box-python-sdk/blob/main/boxsdk/auth/cooperatively_managed_oauth2.py). We run the scripts written with that SDK from cron with the tokens stored in files and no manual authentication (after the initial authentication). Perhaps there is another way to do this, but I didn't see one in the documentation.

**Comment by congminh1254** [comment]
Hi @tribloom 

First of all, thank you for using and testing the new Box Python SDK. We will discuss this topic soon to add support for token storage for all generated SDKs.

We are also looking forward to hearing more feedback from you.

Best regards,
Minh

**Comment by lukaszsocha2** [comment]
Hi @tribloom,
we decide to add this feature soon to our SDK soon. We'll let you know when ready.
Best,
@lukaszsocha2

**Comment by lukaszsocha2** [comment]
Hi @tribloom,
we have just added a new feature, which allows you to define a custom token storage for all authentication methods. Everything is described here: https://github.com/box/box-python-sdk-gen/blob/main/docs/authentication.md#token-storage. I recommend to check if `FileWithInMemoryCacheTokenStorage` would be a suitable for you out of the box. 
If you have any comments or questions regarding this feature or any other, don't hesitate to open a new issue. In a meantime I'm closing this one.
Best,
@lukaszsocha2
