### ISSUE TITLE
I have a question about my collection

### ISSUE THREAD

**Issue by c-rei** [box/box-python-sdk-gen#355]
I can get au information about my collection with box python sdk.
my_collection = client.collection(collection_id="1234567890").get().

But with box-python-sdk-gen, I only can get the favorites collection with,
collections = client.collections.get_collections().

So I can't get the name of my collection by id like old python sdk.

Do you have any way to get my collection information like file or folder,
client.folders.get_folder_by_id(folder_id) ?

Thanks for any advises.

### Versions Used

Python SDK: 1.5.1
Python: 3.10.12

**Comment by mwwoda** [comment]
It seems that this endpoint is [not documented](https://developer.box.com/reference/) in the specification, and most SDK code (including most endpoints) is generated based on it. We will inform the owners of the specification about this problem.

**Comment by lukaszsocha2** [comment]
Hi @c-rei,
we have added support for the required endpoint. It will be soon available in v.1.7.0 release.
Best,
@lukaszsocha2

**Comment by c-rei** [comment]
Hi @lukaszsocha2,
Thanks for your support, I'll try it, and let you known the result.

**Comment by c-rei** [comment]
I've tried this "client.collections.get_collection_by_id(collection_id)" with version 1.7.0, and I got the informations for personal type collection.
Thank you very much.
Best.
