### ISSUE TITLE
Type hint error for enum shared link access

### ISSUE THREAD

**Issue by supermitch** [box/box-python-sdk-gen#385]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ ] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue

Your docs show this example:

```python
client.shared_links_folders.add_share_link_to_folder(
    folder.id,
    "shared_link",
    shared_link=AddShareLinkToFolderSharedLink(
        access=AddShareLinkToFolderSharedLinkAccessField.OPEN.value,
        password="Secret123@",
    ),
)
```

Note the `...OPEN.value`. This is causing a type hint issue, because the literal string `'open'` does not match your definition for `access` argument:

```python
class AddShareLinkToFolderSharedLink(BaseObject):
    def __init__(
        self,
        *,
        access: Optional[AddShareLinkToFolderSharedLinkAccessField] = None,
```

It is expecting `AddShareLinkToFolderSharedLinkAccessField` only, e.g. `.OPEN`

Shouldn't the type hint be `access: Optional[str] = None`?

ps: Your box Developer Forum link is broken, above.

### Steps to Reproduce

Edit your example code in IDE.

### Expected Behavior

I think this is a frustrating issue with Python enum type hinting, per https://stackoverflow.com/a/67292548/515368 this answer.

I think you have to type hint with `Literal[Enum.value1, Enum.Value2, ...]` to fix this, or simply accept type of `str` (my preferred solution).

### Error Message, Including Stack Trace

No errors, just type hinting.

### Screenshots

<img width="1014" alt="image" src="https://github.com/user-attachments/assets/ce886584-ce87-4607-9d2c-b1a720c57040">

### Versions Used

Python SDK: `box-sdk-gen 1.3.0`
Python: `3.10.12`

[sdk-docs]: https://github.com/box/box-python-sdk-gen/tree/main/docs
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-python-sdk-gen/search?type=Issues

**Comment by mwwoda** [comment]
Hi,
Thanks for reporting the issue. Looks like it's specific to some of the language server (like pylance in this case)

Should be fixed by https://github.com/box/box-python-sdk-gen/pull/387

Correct usage of your example shown here https://github.com/box/box-python-sdk-gen/pull/387/files#diff-54de40207be913e76b6a9669129cc318c802c1fdbd0f5ec5c3b055642cc4ac72 (no `.value`)
