### ISSUE TITLE
How do you map online file names to downloaded ZIP file names

### ISSUE THREAD

**Issue by AndersBennedsgaard** [box/box-python-sdk-gen#410]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue

I have many files in Box which includes characters such as `?` and ':'. When downloading the files using `client.zip_downloads.download_zip()`, the characters get replaced with `_`.

Where does this happen (does it happen in the Box API, or through this SDK?), and is it possible to reproduce it locally such that you can map the true file names to the downloaded file names?
Or is it possible to skip this replacement, such that the downloaded file names is the same locally as remote?

### Steps to Reproduce

1. Create a Word document named `is this a file?.docx`.
2. Get the file ID, and create a list of file downloads from it: `zip_downloads=[CreateZipDownloadItems(type=CreateZipDownloadItemsTypeField.FILE, id=file_id)]`
3. Download the ZIP file: `client.zip_downloads.download_zip(zip_downloads, download_file_name=output_path)` (remember to set `output_path`)
4. Extract the ZIP and see that `is this a file?.docx` is replaced with `is this a file_.docx`

### Expected Behavior

The file is extracted to `is this a file?.docx` or there is an easy way to map `is this a file_.docx` to `is this a file?.docx` somehow

### Versions Used

Python SDK: 1.5.1
Python: 3.11

[sdk-docs]: https://github.com/box/box-python-sdk-gen/tree/main/docs
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-python-sdk-gen/search?type=Issues

**Comment by mwwoda** [comment]
We don't change the filename of files inside zip in the SDK. It also happens if you try to create and download zip file via cURL. You can check for yourself by using this sample https://developer.box.com/reference/post-zip-downloads/.

Looks like it's behavior of this API. You could try reaching out to [Community forums](https://support.box.com/hc/en-us/community/topics) or [Box Support](https://support.box.com/hc/en-us) if you want to know more about this behavior.

**Comment by AndersBennedsgaard** [comment]
Damn, I really hoped it was something you guys did, so it was easy to reverse-engineer 😕 
I ended up creating a simple function which runs something like

```python
chars_to_replace = {"?", ":"}  # can be expanded with new characters
for char in chars_to_replace:
    filename= filename.replace(char, '_')
```

and tests this with a set of "true" files against the downloaded files.

I'll close this for now.
