### ISSUE TITLE
SSLError When Uploading Files

### ISSUE THREAD

**Issue by ericasaw** [box/box-python-sdk-gen#413]
### Description of the Issue

I am migrating all of my code from boxsdk to box-sdk-gen and I had a question about an error I would come across from time to time in boxsdk and I am wondering how I can alter my code to prevent the error in box-sdk-gen.

I generally just use the the python box sdk to upload files and give the files permanent download links. I'll run scripts that bulk upload files to folders in Box that can take days to run because the files in the folders can be large or there can be many files in a folder. I use the CCGAuth method because it seemed like the easiest to get working for my simple application of boxsdk.

Occasionally between uploading folders this error would appear:

`Request "POST https://upload.box.com/api/2.0/files/content" failed with SSLError exception: SSLError(MaxRetryError("HTTPSConnectionPool(host='[upload.box.com](http://upload.box.com/)', port=443): Max retries exceeded with url: /api/2.0/files/content (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2406)')))"))
Request "POST https://api.box.com/oauth2/token" failed with ConnectionError exception: ConnectionError(ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))`

I wasn't sure how to interpret this warning since it looks like it comes from the requests package (I assume box sdk uses). It's unclear to me if it has something to do with authorization refresh or an internet connectivity issue, but since my files always seemed to make it to Box okay and the file uploading script didn't stop running, so I haven't worried about it much.

I was wondering if this is an error/warning I should be concerned about or if box sdk/box-sdk-gen retries the request if an error like this occurs? I noticed in the API documentation that the CCGAuth automatically refreshes tokens, so my feeling is that it is not related to that. I just wanted to see if there is something I should be adding to my script to try a file re-upload in the case that this warning triggers from the requests package.

I should note that I am a graduate student in a non-CS field so a lot of the box API terminology is unfamiliar to me so I apologize if this is a simplistic question.

### Steps to Reproduce

Technically this warning/error appeared in boxsdk not box-sdk-gen, but I imagine there must be a similar warning that appears in box-sdk-gen since the error/warning originates from the requests package. I'm only raising the issue here because I imagine that the box sdk GitHub issues are not monitored anymore and I always wondered if I needed to do anything in the case that this warning/error popped up.

**Comment by mwwoda** [comment]
Our old python SDK is still maintained, so feel free to open issue here if you had problem with that package. 

If I understand correctly, besides seeing warnings in console, there are no other issues with uploads? Maybe it's related to unstable internet connection as you mentioned. Are you behind proxy/firewall or is there something that could be affecting the connection?

Also, could you provide sample code/project so that we could reproduce this issue on our side?

**Comment by mwwoda** [comment]
I'm closing this for now as you mentioned it's affecting our old SDK. Please create a new ticket for proper repo, or provide reproduction steps for this SDK if it also occurs there.
