### ISSUE TITLE
How can I search for a metadata enum?

### ISSUE THREAD

**Issue by iareintelligent** [box/box-python-sdk-gen#43]
- [x ] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x ] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x ] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
I have a metadata template with an enum value --  
```
{
    "type": "enum",
    "hidden": false,
    "key": "category",
    "displayName": "Category",
    "options": [
        "Statements",
        "DataOps",
        "Reporting"
    ]
}
```
but when I do a search query, I get zero results:

`
INFO:root:search_query: {'fields': ['id', 'extension', 'metadata.my_enterprise.my_template_key.file_name', 'metadata.my_enterprise.my_template_key.tags', 'metadata.my_enterprise.my_template_key.as_of_date', 'metadata.my_enterprise.my_template_key.file_description', 'metadata.my_enterprise.my_template_key.customAttribute', 'metadata.my_enterprise.my_template_key.created_by', 'metadata.my_enterprise.my_template_key.file_created_at', 'metadata.my_enterprise.my_template_key.category'], 'query': 'category ILIKE :category_value', 'limit': 5, 'marker': None, 'order_by': None, 'query_params': {'category_value': 'DataOps'}, 'from_': 'my_enterprise.my_template_key', 'ancestor_folder_id': '0'}
INFO:root:query_results: <class 'box_sdk_gen.schemas.MetadataQueryResults'> {'entries': [], 'limit': 5}

`

### Steps to Reproduce

perform a query for an enum just like you would for a string. 

### Expected Behavior

See my matching result, based on the "Options".

### Versions Used

Python SDK: 0.2.2
Python: 3.10

[sdk-docs]: https://github.com/box/box-python-sdk-gen/tree/main/docs
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-python-sdk-gen/search?type=Issues

**Comment by lukaszsocha2** [comment]
Hi @iareintelligent, 
have you seen this page: https://developer.box.com/guides/search/metadata-filters/ ? There is a guide how to apply metedata filters for search result. Especially [filter by enum](https://developer.box.com/guides/search/metadata-filters/#filter-by-enum-field) section may be useful. Let me know if you managed to make it work.
Best, 
@lukaszsocha2

**Comment by iareintelligent** [comment]
That still wasnt helpful. I found by trial and error that you cannot do a
like or ilike seqrch for an enum and the query must have =
For example
query = "category = :category"

"category ILIKE :category" will fail woth no explanation.

It would be helpful if your documentation clarified that.

Thanks,

Topher

**Comment by lukaszsocha2** [comment]
Hi,
glad you figured it out. We'll improve our documentation. Thanks.
