### ISSUE TITLE
NoneType Network Response when connection failed.

### ISSUE THREAD

**Issue by JM-CPA-WBD** [box/box-python-sdk-gen#49]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue

In fetch.py, line 116 when trying to check for response.ok, I get an AttributeError saying that response.network_response is a NoneType object. It appears that when __make_request() is called, I'm hitting the RequestException and network_response is being assigned as None. I suppose I must be hitting this if block :

`elif any(
            text in str(request_exc)
            for text in ['Connection aborted', 'Connection broken', 'Connection reset']
        ):`

On line 256 as in my testing I got it to print the RequestException which was "Remote Disconnected".

So the issue is that in the fetch function, it errors out once network_response is assigned as False, yet I'm not given any reason beyond an AttributeError that says response.network_response is a NoneType object. 

### Expected Behavior

I expect there to be some kind of error message telling me if my call has hit the if condition on line 256 (above) as currently it means that I get a None response which I can't do anything with.

### Versions Used

Python SDK: 0.3.0
Python: 3.10

[sdk-docs]: https://github.com/box/box-python-sdk-gen/tree/main/docs
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-python-sdk-gen/search?type=Issues

Thank you!

**Comment by lukaszsocha2** [comment]
Hi @JM-CPA-WBD,
thanks for submitting this issue. You are right, we'll fix this issue soon.
Best,
@lukaszsocha2

**Comment by JM-CPA-WBD** [comment]
No problem! FYI, I managed to bypass this by implementing a retry after 5 seconds. Might be something worth looking into.

Thanks for the response!

**Comment by lukaszsocha2** [comment]
@JM-CPA-WBD By the way, do you have any additional feedback regarding new generated SDK. We are still in beta phase so any feedback is appreciated.

**Comment by lukaszsocha2** [comment]
Hi @JM-CPA-WBD,
this issue is now resolved in new 0.5.0 release.
Best,
@lukaszsocha2
