### ISSUE TITLE
Is urllib3 a needed requirement?

### ISSUE THREAD

**Issue by akrherz** [box/box-python-sdk-gen#55]
Presently, `setup.py` has

```python
install_requires = ['requests', 'requests_toolbelt', 'urllib3<2']
```

Is `urllib3<2` a valid requirement for this library?

**Comment by lukaszsocha2** [comment]
Hi @akrherz,
thanks for reaching us out. We have removed `urllib3` from list of dependencies.
Best,
@lukaszsocha2
